# Generated by Django 2.1.5 on 2019-01-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marker',
            new_name='Artwork',
        ),
    ]
