stages:
  - build

.build:
  image : docker
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build . -f docker/Dockerfile -t jandigarte/django:$DOCKER_TAG --cache-from jandigarte/django:$DOCKER_TAG
    - docker push jandigarte/django:$DOCKER_TAG
  tags:
    - docker

build develop:
  extends: .build
  environment: develop
  only:
    - develop

build staging:
  extends: .build
  environment: staging
  only:
    - master
  except:
    - tags
  
build tag:
  extends: .build
  environment: production
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - "docker build . -f docker/Dockerfile 
            -t jandigarte/django:$CI_COMMIT_TAG
            -t jandigarte/django:$DOCKER_TAG
            -t jandigarte/django:latest"
    - docker push jandigarte/django:$CI_COMMIT_TAG
    - docker push jandigarte/django:$DOCKER_TAG
    - docker push jandigarte/django:latest
  only:
    - tags


