[project]
name = "Jandig"
version = "1.4.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
  "babel~=2.16.0",
  "boto3~=1.36.6",
  "django-cors-headers~=3.14.0",
  "django-environ~=0.12.0",
  "django-extensions~=3.2.3",
  "django-htmx~=1.21.0",
  "django-storages~=1.14.4",
  "django~=5.1.4",
  "djangorestframework~=3.15.2",
  "drf-nested-routers~=0.94.1",
  "factory-boy~=3.3.1",
  "gevent~=24.11.1",
  "gunicorn~=23.0.0",
  "jinja2~=3.1.5",
  "markupsafe~=2.1.1",
  "pillow~=11.1.0",
  "psycopg2-binary~=2.9.3",
  "pymarker~=0.3.1",
  "sentry-sdk~=2.20.0",
  "Sphinx~=8.1.3",
]

[dependency-groups]
dev = [
  "dj-inmemorystorage~=2.1.0",
  "django-debug-toolbar~=4.4.6",
  "invoke~=2.2.0",
  "playwright~=1.49.1",
  "pytest-django~=4.9.0",
  "pytest-playwright~=0.4.4",
  "pytest-xdist~=3.6.1",
  "pytest~=7.4.4",
  "ruff~=0.9.3",
]


[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.test_settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
testpaths = ["src/core", "src/users", "src/blog"]
pythonpath = "src"
addopts="-n4"

[tool.ruff]
exclude = [
  ".git",
  "migrations",
  ".venv",
]
line-length = 88
# Assume Python 3.13
target-version = "py313"

