################################################################
# Configuration sample for Traefik v2.5+
#
# For more information on Traefik with HTTP/3: https://doc.traefik.io/traefik/
#
################################################################

################################################################
# Global configuration
################################################################
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Enable HTTP/3 by specifying the protocol as udp on the secure entrypoint

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443/udp"  # Specify UDP for HTTP/3 support
    [entryPoints.websecure.http3]
      advertisedPort = 443
################################################################
# TLS Configuration
################################################################

[tls]
  [[tls.certificates]]
    certFile = "/path/to/your/cert.crt"
    keyFile = "/path/to/your/key.key"

################################################################
# Providers configuration
################################################################

# Docker provider configuration
[providers.docker]
  watch = true
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

