# Generated by Django 4.1.5 on 2024-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_legacy_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="file",
            field=models.FileField(upload_to="post_images/"),
        ),
    ]
