# Generated by Django 4.1.5 on 2024-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_legacy_clippings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipping",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="clipping",
            name="file",
            field=models.FileField(upload_to="clipping_files/"),
        ),
    ]
