# Generated by Django 5.2.5 on 2025-09-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_clipping_created_alter_clipping_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
