# Generated by Django 6.0 on 2026-01-21 19:32

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_postimage_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clipping',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='clipping',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AddField(
            model_name='clipping',
            name='display_date',
            field=models.DateField(blank=True, null=True, db_index=True),
        ),
        migrations.AddField(
            model_name='clipping',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postimage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
