# Generated by Django 6.0.3 on 2026-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_update_clipping_display_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='excerpt',
        ),
        migrations.AddField(
            model_name='post',
            name='formatted_body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='display_date',
            field=models.DateField(db_index=True),
        ),
    ]
