# Generated by Django 6.0.3 on 2026-05-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_update_clipping_display_dates'),
        ('users', '0012_profileevent_profile_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='display_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='clipping',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddIndex(
            model_name='clipping',
            index=models.Index(fields=['-created'], name='clipping_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='clipping',
            index=models.Index(fields=['-modified'], name='clipping_modified_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created'], name='post_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-modified'], name='post_modified_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['-created'], name='postimage_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['-modified'], name='postimage_modified_desc_idx'),
        ),
    ]
