# Generated by Django 6.1.1 on 2026-09-17 16:36

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_update_formatted_bodies"),
        ("users", "0012_profileevent_profile_insert_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipping",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="clipping",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-created"], name="blog_post_status_created_idx"
            ),
        ),
    ]
