# Generated by Django 6.0.4 on 2026-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_update_formatted_bodies"),
        ("users", "0012_profileevent_profile_insert_insert_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clipping",
            index=models.Index(
                fields=["-created"], name="blog_clippi_created_34f17d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clipping",
            index=models.Index(
                fields=["-modified"], name="blog_clippi_modifie_4aff76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created"], name="blog_post_created_76eb4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-modified"], name="blog_post_modifie_763e41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["-created"], name="blog_postim_created_77e950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["-modified"], name="blog_postim_modifie_ac830e_idx"
            ),
        ),
    ]
