from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import LoginForm
from .views import (
    create_artwork,
    create_exhibit,
    delete,
    download_exhibit,
    edit_artwork,
    edit_exhibit,
    edit_marker,
    edit_object,
    edit_password,
    edit_profile,
    element_get,
    invalid_recovering_email_or_username,
    marker_upload,
    mod,
    mod_delete,
    object_upload,
    permission_denied,
    profile,
    recover_code,
    recover_edit_password,
    recover_password,
    related_content,
    signup,
    wrong_verification_code,
)

urlpatterns = [
    path("signup/", signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login.jinja2",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("recover/", recover_password, name="recover"),
    path("recover-code/", recover_code, name="recover-code"),
    path("profile/", profile, name="profile"),
    path("profile/edit/", edit_profile, name="edit-profile"),
    path("profile/edit-password/", edit_password, name="edit-password"),
    path(
        "wrong-verification-code",
        wrong_verification_code,
        name="wrong-verification-code",
    ),
    path(
        "invalid-recovering-email",
        invalid_recovering_email_or_username,
        name="invalid_recovering_email_or_username",
    ),
    path("recover-edit-password", recover_edit_password, name="recover-edit-password"),
    path("markers/upload/", marker_upload, name="marker-upload"),
    path("objects/upload/", object_upload, name="object-upload"),
    path("element/get/", element_get, name="element-get"),
    path("objects/edit/", edit_object, name="edit-object"),
    path("markers/edit/", edit_marker, name="edit-marker"),
    path("artworks/create/", create_artwork, name="create-artwork"),
    path("artworks/edit/", edit_artwork, name="edit-artwork"),
    path("exhibits/create/", create_exhibit, name="create-exhibit"),
    path("exhibits/edit/", edit_exhibit, name="edit-exhibit"),
    path("download-exhibit", download_exhibit, name="download-exhibit"),
    path("content/delete/", delete, name="delete-content"),
    path("moderator-page/", mod, name="moderator-page"),
    path("permission-denied/", permission_denied, name="permission-denied"),
    path("content/mod-delete/", mod_delete, name="mod-delete-content"),
    path("related-content", related_content, name="related-content"),
]
