# Generated by Django 2.2 on 2019-05-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('augmented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Object')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Marker')),
            ],
        ),
    ]
