# Generated by Django 2.2 on 2019-05-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='source',
            field=models.ImageField(upload_to='markers/'),
        ),
    ]
