# Generated by Django 2.2.2 on 2020-01-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20190715_2232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="source",
            field=models.FileField(upload_to="objects/"),
        ),
    ]
