# Generated by Django 2.0 on 2020-02-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_object_source_20200130_1904"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="title",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="object",
            name="title",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="marker",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.Profile"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="users.Profile"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
