# Generated by Django 2.2.24 on 2021-06-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210620_1950'),
        ('users', '0007_auto_20200220_1425'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='marker',
                    name='owner',
                ),
                migrations.RemoveField(
                    model_name='object',
                    name='owner',
                ),
                migrations.DeleteModel(
                    name='Artwork',
                ),
                migrations.DeleteModel(
                    name='Marker',
                ),
                migrations.DeleteModel(
                    name='Object',
                ),
            ],
            database_operations=[],
        )
    ]
