# Generated by Django 2.2.10 on 2020-11-18 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200213_1934"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artwork2",
        ),
    ]
