# Generated by Django 4.1.2 on 2022-10-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_fake_create_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[       
                migrations.AlterModelTable(
                    name="artwork",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="marker",
                    table=None,
                ),
                migrations.AlterModelTable(
                    name="object",
                    table=None,
                )],
            database_operations=[]),
    ]
