# Generated by Django 4.1.5 on 2023-06-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_artwork_id_alter_exhibit_id_alter_marker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="artworks",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="marker",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="markers",
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ar_objects",
                to="users.profile",
            ),
        ),
    ]
