# Generated by Django 5.1.7 on 2025-04-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_artwork_author_alter_marker_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='file_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='file_size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
