# Generated by Django 5.1.7 on 2025-04-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_update_current_file_size_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='augmented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artworks', to='core.object'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artworks', to='core.marker'),
        ),
    ]
