# Generated by Django 5.2.3 on 2025-07-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_move_old_created_dates_to_new_fields_markers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='object',
            name='uploaded_at',
        ),
    ]
