# Generated by Django 5.2.4 on 2025-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_old_objects_with_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='file_extension',
            field=models.CharField(choices=[('gif', 'GIF'), ('mp4', 'MP4'), ('webm', 'WEBM'), ('glb', 'GLB')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='object',
            name='file_name_original',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='file_extension',
            field=models.CharField(choices=[('gif', 'GIF'), ('mp4', 'MP4'), ('webm', 'WEBM'), ('glb', 'GLB')], max_length=10, null=True, blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='file_name_original',
            field=models.CharField(max_length=255, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='file_size',
            field=models.IntegerField(default=0, null=True, blank=True),
        ),
    ]
