# Generated by Django 5.2.4 on 2025-07-26 14:38

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_null_blank_from_new_fields'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='object',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='object',
            name='update_update',
        ),
        migrations.AddField(
            model_name='object',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='objects/thumbnails/'),
        ),
        migrations.AddField(
            model_name='objectevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='objects/thumbnails/'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='object',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_objectevent" ("author", "created", "file_extension", "file_name_original", "file_size", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position", "rotation", "scale", "source", "thumbnail", "title") VALUES (NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."position", NEW."rotation", NEW."scale", NEW."source", NEW."thumbnail", NEW."title"); RETURN NULL;', hash='6140f77167d3b8a91357f575ab9a668d82740cf3', operation='INSERT', pgid='pgtrigger_insert_insert_25a7e', table='core_object', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='object',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_objectevent" ("author", "created", "file_extension", "file_name_original", "file_size", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position", "rotation", "scale", "source", "thumbnail", "title") VALUES (NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."position", NEW."rotation", NEW."scale", NEW."source", NEW."thumbnail", NEW."title"); RETURN NULL;', hash='13974f86ce00e9bb11124a49272ac8534a07dd53', operation='UPDATE', pgid='pgtrigger_update_update_27852', table='core_object', when='AFTER')),
        ),
    ]
