# Generated by Django 5.2.4 on 2025-07-27 15:38

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_move_object_scale_and_position_to_artworks'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='object',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='object',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='object',
            name='position',
        ),
        migrations.RemoveField(
            model_name='object',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='object',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='objectevent',
            name='position',
        ),
        migrations.RemoveField(
            model_name='objectevent',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='objectevent',
            name='scale',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='object',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_objectevent" ("author", "created", "file_extension", "file_name_original", "file_size", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source", "thumbnail", "title") VALUES (NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source", NEW."thumbnail", NEW."title"); RETURN NULL;', hash='24639068856e681438d212035dd1b920332c8786', operation='INSERT', pgid='pgtrigger_insert_insert_25a7e', table='core_object', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='object',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_objectevent" ("author", "created", "file_extension", "file_name_original", "file_size", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source", "thumbnail", "title") VALUES (NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source", NEW."thumbnail", NEW."title"); RETURN NULL;', hash='6c86603202ed9d072937395df9ddce8594d9865a', operation='UPDATE', pgid='pgtrigger_update_update_27852', table='core_object', when='AFTER')),
        ),
    ]
