# Generated by Django 5.2.4 on 2025-07-27 19:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_object_scale_position_rotation'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='exhibit',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='exhibit',
            name='update_update',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='augmenteds',
            field=models.ManyToManyField(blank=True, related_name='exhibits', to='core.object'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_type',
            field=models.CharField(choices=[('AR', 'Augmented Reality'), ('MR', 'Mixed Reality')], db_index=True, default='AR', max_length=20),
        ),
        migrations.AddField(
            model_name='exhibitevent',
            name='exhibit_type',
            field=models.CharField(choices=[('AR', 'Augmented Reality'), ('MR', 'Mixed Reality')], default='AR', max_length=20),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='artworks',
            field=models.ManyToManyField(blank=True, related_name='exhibits', to='core.artwork'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exhibit',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_exhibitevent" ("created", "exhibit_type", "id", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."created", NEW."exhibit_type", NEW."id", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug"); RETURN NULL;', hash='c0758e1c5c814ae6cf842716f0c4ee5087ecf2f5', operation='INSERT', pgid='pgtrigger_insert_insert_aaa01', table='core_exhibit', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='exhibit',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_exhibitevent" ("created", "exhibit_type", "id", "modified", "name", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug") VALUES (NEW."created", NEW."exhibit_type", NEW."id", NEW."modified", NEW."name", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug"); RETURN NULL;', hash='95a0be188d1660bde11108cf4f17e905aaa64e3b', operation='UPDATE', pgid='pgtrigger_update_update_7b6f5', table='core_exhibit', when='AFTER')),
        ),
    ]
