# Generated by Django 5.2.4 on 2025-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_objects_to_exhibits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='exhibitevent',
            name='slug',
            field=models.SlugField(db_index=False),
        ),
    ]
