# Generated by Django 5.2.4 on 2025-08-13 13:55

import core.models
import django.db.models.deletion
import django_extensions.db.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_exhibit_slug_alter_exhibitevent_slug'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('users', '0012_profileevent_profile_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='sounds/')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=60)),
                ('file_size', models.IntegerField(default=0)),
                ('file_name_original', models.CharField(max_length=255)),
                ('file_extension', models.CharField(choices=[('mp3', 'MP3'), ('ogg', 'OGG')], db_index=True, max_length=10)),
                ('artworks', models.ManyToManyField(blank=True, related_name='sounds', to='core.artwork')),
                ('augmenteds', models.ManyToManyField(blank=True, related_name='sounds', to='core.object')),
                ('exhibits', models.ManyToManyField(blank=True, related_name='sounds', to='core.exhibit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sounds', to='users.profile')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, core.models.ContentMixin),
        ),
        migrations.CreateModel(
            name='SoundEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='sounds/')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=60)),
                ('file_size', models.IntegerField(default=0)),
                ('file_name_original', models.CharField(max_length=255)),
                ('file_extension', models.CharField(choices=[('mp3', 'MP3'), ('ogg', 'OGG')], max_length=10)),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='users.profile')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='core.sound')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sound',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_soundevent" ("author", "created", "file", "file_extension", "file_name_original", "file_size", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."author", NEW."created", NEW."file", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='60ad213f2cae9c1ba07590c4edcfc4bd68aa71d9', operation='INSERT', pgid='pgtrigger_insert_insert_fe2cc', table='core_sound', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sound',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_soundevent" ("author", "created", "file", "file_extension", "file_name_original", "file_size", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."author", NEW."created", NEW."file", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='adc93c06a43156973cae34c15711423ebcb22657', operation='UPDATE', pgid='pgtrigger_update_update_8c5ab', table='core_sound', when='AFTER')),
        ),
    ]
