# Generated by Django 6.0.4 on 2026-04-25 19:08

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_sound_soundevent_remove_artwork_insert_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="object",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="object",
            name="update_update",
        ),
        migrations.AddField(
            model_name="object",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="object",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objectevent",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objectevent",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="object",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_objectevent" ("audio_description", "author", "created", "file_extension", "file_name_original", "file_size", "height", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sound_id", "source", "thumbnail", "title", "width") VALUES (NEW."audio_description", NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."height", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sound_id", NEW."source", NEW."thumbnail", NEW."title", NEW."width"); RETURN NULL;',
                    hash="d7bf940235a51dd1adef2da69d9fda973563e924",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_25a7e",
                    table="core_object",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="object",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_objectevent" ("audio_description", "author", "created", "file_extension", "file_name_original", "file_size", "height", "id", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sound_id", "source", "thumbnail", "title", "width") VALUES (NEW."audio_description", NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."height", NEW."id", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sound_id", NEW."source", NEW."thumbnail", NEW."title", NEW."width"); RETURN NULL;',
                    hash="d1fb1d9e181a30e965a9996e5aa5eebb6303d66e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_27852",
                    table="core_object",
                    when="AFTER",
                ),
            ),
        ),
    ]
