# Generated by Django 6.0.3 on 2026-05-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sound_soundevent_remove_artwork_insert_insert_and_more'),
        ('users', '0012_profileevent_profile_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='artworkevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='artworkevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='exhibitevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='exhibitevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='markerevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='markerevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='object',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='object',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='soundevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='soundevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['-created'], name='artwork_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['-modified'], name='artwork_modified_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['-created'], name='exhibit_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['-modified'], name='exhibit_modified_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibit',
            index=models.Index(fields=['exhibit_type', '-created'], name='exhibit_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='marker',
            index=models.Index(fields=['-created'], name='marker_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='marker',
            index=models.Index(fields=['-modified'], name='marker_modified_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['-created'], name='object_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['-modified'], name='object_modified_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='sound',
            index=models.Index(fields=['-created'], name='sound_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='sound',
            index=models.Index(fields=['-modified'], name='sound_modified_desc_idx'),
        ),
    ]
