# Generated by Django 6.0.4 on 2026-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_sound_soundevent_remove_artwork_insert_insert_and_more"),
        ("users", "0012_profileevent_profile_insert_insert_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["-created"], name="core_artwor_created_f9769d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artwork",
            index=models.Index(
                fields=["-modified"], name="core_artwor_modifie_f2886a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exhibit",
            index=models.Index(
                fields=["-created"], name="core_exhibi_created_a7c2a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exhibit",
            index=models.Index(
                fields=["-modified"], name="core_exhibi_modifie_4e6366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exhibit",
            index=models.Index(
                fields=["exhibit_type", "-created"],
                name="core_exhibi_exhibit_8400bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marker",
            index=models.Index(
                fields=["-created"], name="core_marker_created_5613b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marker",
            index=models.Index(
                fields=["-modified"], name="core_marker_modifie_99c7c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="object",
            index=models.Index(
                fields=["-created"], name="core_object_created_69c39d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="object",
            index=models.Index(
                fields=["-modified"], name="core_object_modifie_f5a679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sound",
            index=models.Index(
                fields=["-created"], name="core_sound_created_ab0a8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sound",
            index=models.Index(
                fields=["-modified"], name="core_sound_modifie_bd78b7_idx"
            ),
        ),
    ]
