# Generated by Django 6.0.6 on 2026-06-29 22:42

import logging

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models
from io import BytesIO

from django.core.files.base import ContentFile
from PIL import Image
from pymarker import (
    generate_marker_from_image,
    remove_borders_from_image,
)

logger = logging.getLogger(__name__)

def generate_variants_for_existing_markers(apps, schema_editor):
    """
    Data migration: For each existing marker, move the original file (with borders)
    into the organized folder as source, then extract the interior by removing
    borders and generate the 3 variants from that.

    The source file is preserved as-is (with borders) so it can be used for
    manual recovery if remove_borders_from_image over-crops.
    """

    Marker = apps.get_model("core", "Marker")

    BLACK_BORDER_PERCENTAGE = 20
    WHITE_BORDER_PERCENTAGE = 3
    MARKER_SIZE = (256, 256)
    THUMB_SIZE = (128, 128)

    for marker in Marker.objects.all().iterator():
        if marker.marker_img and marker.print_img and marker.thumb_img:
            logger.info("Marker %s: already has all variants, skipping.", marker.pk)
            continue

        if not marker.source:
            logger.warning("Marker %s: no source file, skipping.", marker.pk)
            continue

        try:
            storage = marker.source.storage
            old_source_path = marker.source.name

            with marker.source.open("rb") as f:
                file_bytes = f.read()

            current_image = Image.open(BytesIO(file_bytes))
            current_image.load()

            if current_image.mode == "RGBA":
                background = Image.new("RGB", current_image.size, (255, 255, 255))
                background.paste(current_image, mask=current_image.split()[3])
                current_image = background
            elif current_image.mode != "RGB":
                current_image = current_image.convert("RGB")

            # Move source file into organized folder
            ext = old_source_path.rsplit(".", 1)[-1].lower() if "." in old_source_path else "png"
            new_source_path = f"markers/{marker.pk}/source.{ext}"
            _save_to_storage(storage, new_source_path, file_bytes)
            marker.source.name = new_source_path

            # Delete old file at the previous path
            if old_source_path != new_source_path:
                try:
                    if storage.exists(old_source_path):
                        storage.delete(old_source_path)
                except Exception:
                    pass

            # Extract interior by removing borders for variant generation
            interior_image = remove_borders_from_image(current_image)

            # 2. Generate marker image (black border only, 256x256)
            marker_full = generate_marker_from_image(
                interior_image,
                black_border_percentage=BLACK_BORDER_PERCENTAGE,
                white_border_percentage=0,
            )
            marker_resized = marker_full.resize(MARKER_SIZE, Image.LANCZOS)
            marker_blob = BytesIO()
            marker_resized.save(marker_blob, "PNG")
            marker_img_path = f"markers/{marker.pk}/marker.png"
            _save_to_storage(storage, marker_img_path, marker_blob.getvalue())
            marker.marker_img.name = marker_img_path

            # 3. Generate print image (black + white border, original size)
            print_image = generate_marker_from_image(
                interior_image,
                black_border_percentage=BLACK_BORDER_PERCENTAGE,
                white_border_percentage=WHITE_BORDER_PERCENTAGE,
            )
            print_blob = BytesIO()
            print_image.save(print_blob, "PNG")
            print_img_path = f"markers/{marker.pk}/print.png"
            _save_to_storage(storage, print_img_path, print_blob.getvalue())
            marker.print_img.name = print_img_path

            # 4. Generate thumbnail (128x128)
            thumb_image = marker_full.resize(THUMB_SIZE, Image.LANCZOS)
            thumb_blob = BytesIO()
            thumb_image.save(thumb_blob, "PNG")
            thumb_img_path = f"markers/{marker.pk}/thumb.png"
            _save_to_storage(storage, thumb_img_path, thumb_blob.getvalue())
            marker.thumb_img.name = thumb_img_path

            # 5. Update file_size (print image size for download)
            marker.file_size = len(print_blob.getvalue())

            marker.save()
            logger.info("Marker %s: variants generated successfully.", marker.pk)

        except Exception as e:
            logger.error("Marker %s: failed to generate variants: %s", marker.pk, e)
            continue


def _save_to_storage(storage, path, content_bytes):
    """Save content to storage, deleting existing file first for idempotency."""
    try:
        if storage.exists(path):
            storage.delete(path)
    except Exception:
        pass
    storage.save(path, ContentFile(content_bytes))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sound_soundevent_remove_artwork_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='marker',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='marker',
            name='update_update',
        ),
        migrations.AddField(
            model_name='marker',
            name='marker_img',
            field=models.ImageField(blank=True, upload_to='markers/'),
        ),
        migrations.AddField(
            model_name='marker',
            name='print_img',
            field=models.ImageField(blank=True, upload_to='markers/'),
        ),
        migrations.AddField(
            model_name='marker',
            name='thumb_img',
            field=models.ImageField(blank=True, upload_to='markers/'),
        ),
        migrations.AddField(
            model_name='markerevent',
            name='marker_img',
            field=models.ImageField(blank=True, upload_to='markers/'),
        ),
        migrations.AddField(
            model_name='markerevent',
            name='print_img',
            field=models.ImageField(blank=True, upload_to='markers/'),
        ),
        migrations.AddField(
            model_name='markerevent',
            name='thumb_img',
            field=models.ImageField(blank=True, upload_to='markers/'),
        ),
        migrations.RunPython(
            generate_variants_for_existing_markers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
