# Generated by Django 6.0.6 on 2026-06-30 18:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_marker_image_variants'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='marker',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "marker_img", "modified", "owner_id", "patt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."marker_img", NEW."modified", NEW."owner_id", NEW."patt", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."print_img", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;', hash='2ce793af280ef592356a603005a51663cbaea53e', operation='INSERT', pgid='pgtrigger_insert_insert_719b2', table='core_marker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='marker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "marker_img", "modified", "owner_id", "patt", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."marker_img", NEW."modified", NEW."owner_id", NEW."patt", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."print_img", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;', hash='dc69672686ecc014795e197390b4fd41b9a2c58e', operation='UPDATE', pgid='pgtrigger_update_update_9a032', table='core_marker', when='AFTER')),
        ),
    ]
