# Generated by Django 6.0.6 on 2026-07-01 15:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_relocate_object_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='audio_description',
            field=models.FileField(blank=True, null=True, upload_to=core.models.object_audio_description_path),
        ),
        migrations.AlterField(
            model_name='object',
            name='source',
            field=models.FileField(upload_to=core.models.object_source_path),
        ),
        migrations.AlterField(
            model_name='object',
            name='spritesheet_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.object_spritesheet_path),
        ),
        migrations.AlterField(
            model_name='object',
            name='spritesheet_metadata',
            field=models.FileField(blank=True, null=True, upload_to=core.models.object_spritesheet_metadata_path),
        ),
        migrations.AlterField(
            model_name='object',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.object_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='audio_description',
            field=models.FileField(blank=True, null=True, upload_to=core.models.object_audio_description_path),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='source',
            field=models.FileField(upload_to=core.models.object_source_path),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='spritesheet_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.object_spritesheet_path),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='spritesheet_metadata',
            field=models.FileField(blank=True, null=True, upload_to=core.models.object_spritesheet_metadata_path),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.object_thumbnail_path),
        ),
    ]
