# Generated by Django 6.0.6 on 2026-07-01 16:41

import logging

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations

logger = logging.getLogger(__name__)


def delete_patt_files_from_storage(apps, schema_editor):
    """Remove all .patt files from storage (patts/ folder and markers/{id}/ folders)."""
    from django.core.files.storage import default_storage

    # 1. Delete all files in the patts/ folder
    try:
        dirs, files = default_storage.listdir("patts")
        for filename in files:
            path = f"patts/{filename}"
            try:
                default_storage.delete(path)
                logger.info("Deleted: %s", path)
            except Exception as e:
                logger.warning("Failed to delete %s: %s", path, e)
    except Exception:
        logger.info("No patts/ folder found in storage, skipping.")

    # 2. Delete marker.patt files inside markers/{id}/ folders
    try:
        dirs, _ = default_storage.listdir("markers")
        for folder in dirs:
            patt_path = f"markers/{folder}/marker.patt"
            try:
                if default_storage.exists(patt_path):
                    default_storage.delete(patt_path)
                    logger.info("Deleted: %s", patt_path)
            except Exception as e:
                logger.warning("Failed to delete %s: %s", patt_path, e)
    except Exception:
        logger.info("No markers/ folder found in storage, skipping.")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_object_upload_to_paths'),
    ]

    operations = [
        migrations.RunPython(
            delete_patt_files_from_storage,
            reverse_code=migrations.RunPython.noop,
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='marker',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='marker',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='patt',
        ),
        migrations.RemoveField(
            model_name='markerevent',
            name='patt',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='marker',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "marker_img", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."marker_img", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."print_img", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;', hash='60a60cd514500ad6841b68285b8ce5b046896613', operation='INSERT', pgid='pgtrigger_insert_insert_719b2', table='core_marker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='marker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "marker_img", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."marker_img", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."print_img", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;', hash='5c1690a55abfaf3b0c990af977fef45e79f58ccb', operation='UPDATE', pgid='pgtrigger_update_update_9a032', table='core_marker', when='AFTER')),
        ),
    ]
