# Generated by Django 6.0.6 on 2026-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_marker_patt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='file_extension',
            field=models.CharField(choices=[('gif', 'GIF'), ('png', 'PNG'), ('mp4', 'MP4'), ('webm', 'WEBM'), ('glb', 'GLB')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='objectevent',
            name='file_extension',
            field=models.CharField(choices=[('gif', 'GIF'), ('png', 'PNG'), ('mp4', 'MP4'), ('webm', 'WEBM'), ('glb', 'GLB')], max_length=10),
        ),
    ]
