# Generated by Django 6.0.6 on 2026-07-11 18:46

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_fix_object_file_paths'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='marker',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='marker',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='object',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='object',
            name='update_update',
        ),
        migrations.AddField(
            model_name='marker',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='markerevent',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectevent',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='marker',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "in_use", "marker_img", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."in_use", NEW."marker_img", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."print_img", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;', hash='2c3fdd0b348936645e032c4c49e0838cd3e44278', operation='INSERT', pgid='pgtrigger_insert_insert_719b2', table='core_marker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='marker',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "in_use", "marker_img", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."in_use", NEW."marker_img", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."print_img", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;', hash='38a2cfefc675e85bb8c6d23e059e389feea4dfbd', operation='UPDATE', pgid='pgtrigger_update_update_9a032', table='core_marker', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='object',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_objectevent" ("audio_description", "author", "created", "file_extension", "file_name_original", "file_size", "height", "id", "in_use", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sound_id", "source", "spritesheet_file", "spritesheet_metadata", "thumbnail", "title", "width") VALUES (NEW."audio_description", NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."height", NEW."id", NEW."in_use", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."sound_id", NEW."source", NEW."spritesheet_file", NEW."spritesheet_metadata", NEW."thumbnail", NEW."title", NEW."width"); RETURN NULL;', hash='5759af6ab3d34b103769f516817f9c3778abdaf9', operation='INSERT', pgid='pgtrigger_insert_insert_25a7e', table='core_object', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='object',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_objectevent" ("audio_description", "author", "created", "file_extension", "file_name_original", "file_size", "height", "id", "in_use", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "sound_id", "source", "spritesheet_file", "spritesheet_metadata", "thumbnail", "title", "width") VALUES (NEW."audio_description", NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."height", NEW."id", NEW."in_use", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."sound_id", NEW."source", NEW."spritesheet_file", NEW."spritesheet_metadata", NEW."thumbnail", NEW."title", NEW."width"); RETURN NULL;', hash='13304478232c11c024ce6631bae12088989ac7c6', operation='UPDATE', pgid='pgtrigger_update_update_27852', table='core_object', when='AFTER')),
        ),
    ]
