# Generated by Django 6.0.6 on 2026-07-11 18:47

from django.db import migrations


def populate_in_use(apps, schema_editor):
    Marker = apps.get_model("core", "Marker")
    Object = apps.get_model("core", "Object")
    Artwork = apps.get_model("core", "Artwork")

    used_marker_ids = Artwork.objects.values_list("marker_id", flat=True).distinct()
    Marker.objects.filter(pk__in=used_marker_ids).update(in_use=True)

    used_object_ids = Artwork.objects.values_list("augmented_id", flat=True).distinct()
    Object.objects.filter(pk__in=used_object_ids).update(in_use=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_in_use_field_to_marker_and_object'),
    ]

    operations = [
        migrations.RunPython(populate_in_use, migrations.RunPython.noop),
    ]
