# Generated by Django 6.0.6 on 2026-07-11 18:55

from django.db import migrations


def populate_is_used_by_other_user(apps, schema_editor):
    Marker = apps.get_model("core", "Marker")
    Object = apps.get_model("core", "Object")
    Artwork = apps.get_model("core", "Artwork")

    for marker in Marker.objects.all():
        if Artwork.objects.filter(marker=marker).exclude(author=marker.owner).exists():
            marker.is_used_by_other_user = True
            marker.save(update_fields=["is_used_by_other_user"])

    for obj in Object.objects.all():
        if Artwork.objects.filter(augmented=obj).exclude(author=obj.owner).exists():
            obj.is_used_by_other_user = True
            obj.save(update_fields=["is_used_by_other_user"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_is_used_by_other_user_field'),
    ]

    operations = [
        migrations.RunPython(populate_is_used_by_other_user, migrations.RunPython.noop),
    ]
