# Generated by Django 6.0.6 on 2026-07-11 19:05

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_populate_is_used_by_other_user_field'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='sound',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='sound',
            name='update_update',
        ),
        migrations.AddField(
            model_name='sound',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sound',
            name='is_used_by_other_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soundevent',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soundevent',
            name='is_used_by_other_user',
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sound',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "core_soundevent" ("author", "created", "file", "file_extension", "file_name_original", "file_size", "id", "in_use", "is_used_by_other_user", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."author", NEW."created", NEW."file", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."in_use", NEW."is_used_by_other_user", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."title"); RETURN NULL;', hash='cc51980a6dcdc729109bf15f4be631e1aa1b398e', operation='INSERT', pgid='pgtrigger_insert_insert_fe2cc', table='core_sound', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='sound',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "core_soundevent" ("author", "created", "file", "file_extension", "file_name_original", "file_size", "id", "in_use", "is_used_by_other_user", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "title") VALUES (NEW."author", NEW."created", NEW."file", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."id", NEW."in_use", NEW."is_used_by_other_user", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."title"); RETURN NULL;', hash='4d24c37be50a81ac25831f917e6380db10013293', operation='UPDATE', pgid='pgtrigger_update_update_8c5ab', table='core_sound', when='AFTER')),
        ),
    ]
