# Generated by Django 6.0.6 on 2026-07-11 19:06

from django.db import migrations


def populate_sound_flags(apps, schema_editor):
    Sound = apps.get_model("core", "Sound")
    Artwork = apps.get_model("core", "Artwork")
    Object = apps.get_model("core", "Object")
    Exhibit = apps.get_model("core", "Exhibit")

    for sound in Sound.objects.all():
        is_in_use = (
            Artwork.objects.filter(sound=sound).exists()
            or Object.objects.filter(sound=sound).exists()
            or Exhibit.objects.filter(sounds=sound).exists()
        )
        used_by_other = (
            Artwork.objects.filter(sound=sound).exclude(author=sound.owner).exists()
            or Object.objects.filter(sound=sound).exclude(owner=sound.owner).exists()
            or Exhibit.objects.filter(sounds=sound).exclude(owner=sound.owner).exists()
        )
        if is_in_use or used_by_other:
            Sound.objects.filter(pk=sound.pk).update(
                in_use=is_in_use, is_used_by_other_user=used_by_other
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_in_use_fields_to_sound'),
    ]

    operations = [
        migrations.RunPython(populate_sound_flags, migrations.RunPython.noop),
    ]
