# Generated by Django 6.1.1 on 2026-09-17 14:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_populate_sound_in_use_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sound",
            name="file",
            field=models.FileField(upload_to=core.models.sound_file_path),
        ),
        migrations.AlterField(
            model_name="soundevent",
            name="file",
            field=models.FileField(upload_to=core.models.sound_file_path),
        ),
    ]
