# Generated by Django 6.1.1 on 2026-09-17 16:36

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_populate_sound_in_use_fields"),
        ("users", "0012_profileevent_profile_insert_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="marker",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="marker",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="sound",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
        migrations.AddIndex(
            model_name="exhibit",
            index=models.Index(
                fields=["exhibit_type", "-created"],
                name="core_exhibit_type_created_idx",
            ),
        ),
    ]
