# Generated by Django 6.1.1 on 2026-09-17 15:21

import core.models
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_populate_sound_in_use_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bug", "Report a bug"),
                            ("feature", "Request a feature"),
                        ],
                        db_index=True,
                        default="bug",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(max_length=5000)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.feedback_attachment_path,
                    ),
                ),
                (
                    "handled",
                    models.BooleanField(
                        default=False,
                        help_text="Tick once this report has been triaged.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "feedback",
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
