# Generated by Django 6.1.1 on 2026-09-17 18:12

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_add_slug_to_marker_object_artwork"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="artwork",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="artwork",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="marker",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="marker",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="object",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="object",
            name="update_update",
        ),
        migrations.AddField(
            model_name="artworkevent",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=80),
        ),
        migrations.AddField(
            model_name="markerevent",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=80),
        ),
        migrations.AddField(
            model_name="objectevent",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, max_length=80),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="artwork",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_artworkevent" ("augmented_id", "author_id", "created", "description", "id", "marker_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position_x", "position_y", "scale_x", "scale_y", "slug", "sound_id", "title") VALUES (NEW."augmented_id", NEW."author_id", NEW."created", NEW."description", NEW."id", NEW."marker_id", NEW."modified", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."position_x", NEW."position_y", NEW."scale_x", NEW."scale_y", NEW."slug", NEW."sound_id", NEW."title"); RETURN NULL;',
                    hash="5e63367fae81726ac16a46d352593ae1168af728",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_65595",
                    table="core_artwork",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="artwork",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_artworkevent" ("augmented_id", "author_id", "created", "description", "id", "marker_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position_x", "position_y", "scale_x", "scale_y", "slug", "sound_id", "title") VALUES (NEW."augmented_id", NEW."author_id", NEW."created", NEW."description", NEW."id", NEW."marker_id", NEW."modified", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."position_x", NEW."position_y", NEW."scale_x", NEW."scale_y", NEW."slug", NEW."sound_id", NEW."title"); RETURN NULL;',
                    hash="e9552c93dd966d86637b42bc885edeb99574e593",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_1ac7c",
                    table="core_artwork",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="marker",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "in_use", "is_used_by_other_user", "marker_img", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "slug", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."in_use", NEW."is_used_by_other_user", NEW."marker_img", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."print_img", NEW."slug", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;',
                    hash="2c58d9fb44016e14cab644eaf1f1f09296c5a5d3",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_719b2",
                    table="core_marker",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="marker",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_markerevent" ("author", "created", "file_size", "id", "in_use", "is_used_by_other_user", "marker_img", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "print_img", "slug", "source", "thumb_img", "title") VALUES (NEW."author", NEW."created", NEW."file_size", NEW."id", NEW."in_use", NEW."is_used_by_other_user", NEW."marker_img", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."print_img", NEW."slug", NEW."source", NEW."thumb_img", NEW."title"); RETURN NULL;',
                    hash="a20e0970e5fa5c2c399575dd7f2cba6e20db9b6e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_9a032",
                    table="core_marker",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="object",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_objectevent" ("audio_description", "author", "created", "file_extension", "file_name_original", "file_size", "height", "id", "in_use", "is_used_by_other_user", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "sound_id", "source", "spritesheet_file", "spritesheet_metadata", "thumbnail", "title", "width") VALUES (NEW."audio_description", NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."height", NEW."id", NEW."in_use", NEW."is_used_by_other_user", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."slug", NEW."sound_id", NEW."source", NEW."spritesheet_file", NEW."spritesheet_metadata", NEW."thumbnail", NEW."title", NEW."width"); RETURN NULL;',
                    hash="dd7898ed958ac123fbbe20c2568791dea1f5319a",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_25a7e",
                    table="core_object",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="object",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_objectevent" ("audio_description", "author", "created", "file_extension", "file_name_original", "file_size", "height", "id", "in_use", "is_used_by_other_user", "modified", "owner_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "slug", "sound_id", "source", "spritesheet_file", "spritesheet_metadata", "thumbnail", "title", "width") VALUES (NEW."audio_description", NEW."author", NEW."created", NEW."file_extension", NEW."file_name_original", NEW."file_size", NEW."height", NEW."id", NEW."in_use", NEW."is_used_by_other_user", NEW."modified", NEW."owner_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."slug", NEW."sound_id", NEW."source", NEW."spritesheet_file", NEW."spritesheet_metadata", NEW."thumbnail", NEW."title", NEW."width"); RETURN NULL;',
                    hash="29621b17da2a972b7b6334e955fe8c8c37fa1065",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_27852",
                    table="core_object",
                    when="AFTER",
                ),
            ),
        ),
    ]
