from django.conf import settings
from django.urls import include, path, re_path

from core.views.static_views import (
    community,
    documentation,
    favicon,
    health_check,
    home_old,
    home_new,
    manifest,
    marker_generator,
    me_hotsite,
    robots_txt,
    service_worker,
)
from core.views.views import (
    artwork_preview,
    collection,
    create_artwork,
    create_or_edit_ar_exhibit,
    create_or_edit_mr_exhibit,
    delete,
    edit_artwork,
    edit_marker,
    edit_object,
    edit_sound,
    exhibit,
    exhibit_detail,
    exhibit_select,
    get_element,
    marker_preview,
    marker_upload,
    object_upload,
    related_content,
    see_all,
    sound_upload,
)

urlpatterns = [
    path("", home_new, name="home"),
    path("arviewer/", home_old, name="home-old"),
    path("artwork/", artwork_preview, name="artwork-preview"),
    path("artworks/create/", create_artwork, name="create-artwork"),
    path("artworks/edit/", edit_artwork, name="edit-artwork"),
    path("collection/", collection, name="collection"),
    path("community/", community, name="community"),
    path("content/delete/", delete, name="delete-content"),
    path("documentation/", documentation, name="documentation"),
    path("exhibit_select/", exhibit_select, name="exhibit_select"),
    path("exhibit/", exhibit_detail, name="exhibit-detail"),
    path("exhibits/create-ar/", create_or_edit_ar_exhibit, name="create-ar-exhibit"),
    path("exhibits/edit-ar/", create_or_edit_ar_exhibit, name="edit-ar-exhibit"),
    path("exhibits/create-mr/", create_or_edit_mr_exhibit, name="create-mr-exhibit"),
    path("exhibits/edit-mr/", create_or_edit_mr_exhibit, name="edit-mr-exhibit"),
    path("generator/", marker_generator, name="marker-generator"),
    path("marker/", marker_preview, name="marker-preview"),
    path("markers/edit/", edit_marker, name="edit-marker"),
    path("markers/upload/", marker_upload, name="marker-upload"),
    path("objects/edit/", edit_object, name="edit-object"),
    path("objects/upload/", object_upload, name="object-upload"),
    path("sounds/edit/", edit_sound, name="edit-sound"),
    path("sounds/upload/", sound_upload, name="sound-upload"),
    path("elements/", get_element, name="get-element"),
    re_path(
        r"^(me|ME)\/?$",
        me_hotsite,
        name="mitologia-extendida",
    ),
    path("related-content", related_content, name="related-content"),
    path("sw.js", service_worker, name="sw"),
    path("manifest.json", manifest, name="manifest"),
    path("i18n/", include("django.conf.urls.i18n")),
    re_path(
        r"^see_all(?:/(?P<which>[a-zA-Z]+))?/$",
        see_all,
        name="see_all",
    ),
    path("robots.txt", robots_txt, name="robots_txt"),
    path("favicon.ico", favicon, name="favicon"),
    path(settings.HEALTH_CHECK_URL, health_check, name="health_check"),
    path("<slug:slug>/", exhibit, name="exhibit"),
]
