from django.conf import settings
from django.urls import include, path, re_path

from core.views.static_views import (
    community,
    documentation,
    favicon,
    health_check,
    home,
    manifest,
    marker_generator,
    me_hotsite,
    robots_txt,
    service_worker,
)
from core.views.views import (
    artwork_preview,
    collection,
    create_artwork,
    create_exhibit,
    delete,
    edit_artwork,
    edit_exhibit,
    edit_marker,
    edit_object,
    exhibit,
    exhibit_detail,
    exhibit_select,
    get_element,
    marker_upload,
    object_upload,
    related_content,
    see_all,
)

urlpatterns = [
    path("", home, name="home"),
    path("artwork/", artwork_preview, name="artwork-preview"),
    path("artworks/create/", create_artwork, name="create-artwork"),
    path("artworks/edit/", edit_artwork, name="edit-artwork"),
    path("collection/", collection, name="collection"),
    path("community/", community, name="community"),
    path("content/delete/", delete, name="delete-content"),
    path("documentation/", documentation, name="documentation"),
    path("exhibit_select/", exhibit_select, name="exhibit_select"),
    path("exhibit/", exhibit_detail, name="exhibit-detail"),
    path("exhibits/create/", create_exhibit, name="create-exhibit"),
    path("exhibits/edit/", edit_exhibit, name="edit-exhibit"),
    path("generator/", marker_generator, name="marker-generator"),
    path("markers/edit/", edit_marker, name="edit-marker"),
    path("markers/upload/", marker_upload, name="marker-upload"),
    path("objects/edit/", edit_object, name="edit-object"),
    path("objects/upload/", object_upload, name="object-upload"),
    path("elements/", get_element, name="get-element"),
    re_path(
        r"^(me|ME)\/?$",
        me_hotsite,
        name="mitologia-extendida",
    ),
    path("related-content", related_content, name="related-content"),
    path("sw.js", service_worker, name="sw"),
    path("manifest.json", manifest, name="manifest"),
    path("i18n/", include("django.conf.urls.i18n")),
    re_path(
        r"^see_all(?:/(?P<which>[a-zA-Z]+))?/$",
        see_all,
        name="see_all",
    ),
    path("robots.txt", robots_txt, name="robots_txt"),
    path("favicon.ico", favicon, name="favicon"),
    path(settings.HEALTH_CHECK_URL, health_check, name="health_check"),
    path("<slug:slug>/", exhibit, name="exhibit"),
]
