# Generated by Django 2.1.2 on 2018-10-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('scale', models.CharField(default='1 1', max_length=50)),
                ('position', models.CharField(default='0 0 0', max_length=50)),
                ('patt', models.CharField(default='hiro', max_length=50)),
                ('gif', models.CharField(default='peixe', max_length=50)),
                ('rotation', models.CharField(default='270 0 0', max_length=50)),
            ],
        ),
    ]
