# Generated by Django 2.2.1 on 2019-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibit",
            name="creation_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
