# Generated by Django 2.2 on 2019-05-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artwork',
            new_name='Artwork2',
        ),
    ]
