# Generated by Django 2.1.4 on 2018-12-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pwa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marker',
            new_name='Artwork',
        ),
    ]
